version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:1.10.3
    restart: always
    ports: 
        - 443:443
        - 80:80
    environment:
        WEBROOT: /var/www/html/src
        RUN_SCRIPTS: 1
    volumes:
        - .:/var/www/html